# Generated by Django 3.2 on 2022-10-21 18:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('recipients', models.JSONField(blank=True, null=True, verbose_name='recipients')),
                ('recipients_file', models.FileField(null=True, upload_to='uploads/', verbose_name='recipients')),
                ('content', models.TextField(verbose_name='content')),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Saved'), (3, 'Sent')], default=1, verbose_name='status')),
                ('status_updated_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.IntegerField(choices=[(1, 'email'), (2, 'web'), (3, 'app'), (4, 'sms')], default=1, verbose_name='channel')),
                ('check_timezone', models.BooleanField(default=1, verbose_name='timezone checking')),
                ('check_relevance', models.BooleanField(default=1, verbose_name='relevance checking')),
                ('group', models.IntegerField(choices=[(1, 'info')], default=1, verbose_name='message group')),
                ('template', models.FileField(blank=True, default='base.html', null=True, upload_to='uploads/', verbose_name='template')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'notifications"."messages',
            },
        ),
    ]
